### ISSUE TITLE
RestMixin Promise Problem maybe

### ISSUE THREAD

**Issue by thxmike** [agmen-hu/node-datapumps#13]
In the following example there appears to be a problem with the response.
data_pump
        .mixin(datapumps.mixin.RestMixin)
        .process(function (data) {

            this.post(target_service_end_point, { 
                multipart: false, 
                headers: {
                    'Content-Type' : 'application/json', 
                    'X-ApiKey' :   target_service_end_point_shared_secret
                }, 
                data: test_record_json
            }).then(function(result, response) {

                console.log(result);
                console.log(response);
                return this.copy(result, response);

            }.bind(this));

        }).start()
        .whenFinished().then(function(result, response){
 
            console.log(result);
            console.log(response);

    });
I attempted to debug it and I found that the RestMixin does have a valid response:
return restler[methodName].apply(restler, methodArgs).on('complete', function(result, response) {
          if (result instanceof Error) {
            return reject(result);
          } else {
            return resolve(result, response);
          }
        });
It appears however, when it gets into resolve. something is changing the response to undefined. When I get back into the promise chain, 
i.e. 
).then(function(result, response) {

                console.log(result);
                console.log(response);
'response' is undefined

I am stumped on this one and not sure how to debug it. Any assistance would be appreciated.

**Comment by novaki** [comment]
My fix for #12 did not work, as a promise can only have one return value. In 0.3.27, the response object is returned, and result is added to it in .result property. Please check the docs here: http://agmen-hu.github.io/node-datapumps/docs/mixin/RestMixin.html.

**Comment by thxmike** [comment]
Awesome!!!.  This works greate
