### ISSUE TITLE
Whenfinished Promise

### ISSUE THREAD

**Issue by thxmike** [agmen-hu/node-datapumps#14]
In the follow abbreviated example, everything appears to be working as expected. However after further investigation, it appear we never get a response from the whenFinished promise.
The line console.log("The processing is finished"); never executes and there is nothing reported in logErrorsToConsole()

This does not appear to be by design but wanted to make nothing is missed.

data_pump
        .mixin(datapumps.mixin.RestMixin)
        .process(function (data) {

            console.log(target_service_end_point)
           return  this.post(target_service_end_point, { 
                multipart: false, 
                headers: {
                    'Content-Type' : 'application/json', 
                    'X-ApiKey' :   target_service_end_point_shared_secret
                }, 
                data: record
            }).then(function(response) {
 
                if(response.statusCode == 201)
                {
                    candidate_map.push({ "source":data.id, "destination":response.result.id } )
                }
                //console.log(response);
                return this.copy(response);
            }.bind(this));

        }).logErrorsToConsole().start()
        .whenFinished().then(function(data){
            
            console.log("The processing is finished");
    });
    console.log(candidate_map);

**Comment by thxmike** [comment]
Not to be a pain but is there any update on this item?

**Comment by novaki** [comment]
Maybe the docs are not clear on this, so I'll only close this ticket after updating the docs. `.whenFinished()` promise is fulfilled when the pump is finished. A pump is considered finished when all items from its input buffer are read and it's output buffer is empty (some other pump read it, or it was not written at all).

Basically, you don't need to write the output buffer of your pump, if there isn't any pump reading from it (`.from()` method). Otherwise, your output buffer will not become empty and pumping will never stop.
```js
var candidate_map = [];
data_pump
  .mixin(datapumps.mixin.RestMixin)
  .process(function (data) {
    return this.post(target_service_end_point, { 
      multipart: false, 
      headers: {
        'Content-Type' : 'application/json', 
        'X-ApiKey' :   target_service_end_point_shared_secret
      }, 
      data: record
    }).then(function(response) {
      if(response.statusCode == 201) {
        candidate_map.push({ "source":data.id, "destination":response.result.id });
      }
    }.bind(this))
  })
  .logErrorsToConsole()
  .start()
  .whenFinished().then(function(data){
    console.log("The processing is finished");
    console.log(candidate_map);
  });
```

**Comment by thxmike** [comment]
OK, the example is incomplete and we do have data going into the pump in a from. Here is a more full  example that shows the use of from(). I have removed some sensitive areas of the example, most of this works but we do not get to whenFinished:

var datapumps = require('datapumps');
    var mssql = require('mssql');
    var candidate_map = require('../candidate/candidate_map');
    var source_sql_query = '< some sql statement>';

    var config = {
        user: source_database_server_user,
        password: source_database_server_password,
        server: source_server, // You can use 'localhost\\instance' to connect to named instance
        database: source_database,
        //stream: true, // You can enable streaming globally
        requestTimeout: source_server_database_query_timeout,
        options: {
            encrypt: true // Use this if you're on Windows Azure
        }
    }

    var connection = new mssql.Connection(config, function (err) {
        // ... error checks
        if (err) {
            console.log(err);
            return;
        }
        var request = connection.request();
        request.stream = true;
        //Parameter
        //request.input('locationid', mssql.Int, 6);
        var sql_query = source_sql_query;

        request.query(sql_query,
            function (err, recordSet) {
                // ... error checks
                if (err) {
                    console.log(err);
                    return;
                }
            });

        request.on('row', function(row) {
            data_pump.from().writeAsync(row);

        });

    });
    // Setup the data pump
    var data_pump = new datapumps.Pump().from(new datapumps.Buffer());

    //Process the Post operation
    data_pump
        .mixin(datapumps.mixin.RestMixin)
        .process(function (data) {
            var record = '<some json looking data';

                return this.post(target_service_end_point, { 
                multipart: false, 
                headers: {
                    'Content-Type' : 'application/json', 
                    'X-ApiKey' :   target_service_end_point_shared_secret
                }, 
                data: record
            }).then(function(response) {

                console.log(data.Email + '*******************************************');
                console.log(response.result);
                return this.copy(response);
            }.bind(this));

        }).logErrorsToConsole().start()
        .whenFinished().then(function(data){
         console.log("The processing is finished");    
         console.log(data);
    });

**Comment by novaki** [comment]
You need to tell when the sql query is done:
```js
    request.on('done', function(row) {
        data_pump.from().seal();
    });
```

The `.seal()` method must be called on a buffer when it will receive no more data. 

So, a pump is considered finished (i.e. `.whenFinished()` promise is fulfilled) when its input buffer is sealed and empty and it's output buffer is empty (some other pump read it, or it was not written at all). The pump will automatically seal output buffers when its finished.

**Comment by thxmike** [comment]
Thank you. I was able to resolve this issue with the recommendation above.
