### ISSUE TITLE
Output buffer does not extend nor clears, records above 10

### ISSUE THREAD

**Issue by thxmike** [agmen-hu/node-datapumps#17]
We are experiencing a problem when using records above 10, for the input buffer, from(), we had to extend the size to a large number (2000 in our example). However, we noticed that the when the output buffer reaches 10, the system stops. We assumed the output buffer would pop items form its container but it is not doing this. Below is an example of the node module we have been using. 
You can see we are reading from a database and attempting to write to the Restful endpoints. We also notice this never gets to the WhenFinished() promise.

module.exports = (function(rec14AuthToken) {
    var fs = require('fs');
    var path = require('path');
    var datapumps = require('datapumps');
    var mssql = require('mssql');
    var config = require('../../config');
    var candidateSourceSQL = fs.readFileSync(path.join(__dirname, 'candidateSourceQuery.sql'), 'utf8');
    var rec14APIUrlCandidates = config.rec14.baseUrl + '/' + config.rec14.tenant + '/api/candidates/';

    var sqlConfig = {
        user: config.rec10.dbServerUserName,
        password: config.rec10.dbServerPassword,
        server: config.rec10.dbServer,
        database: config.rec10.db,
        requestTimeout: config.rec10.dbServerCommandTimeout,
        options: {
            encrypt: true
        }
    };

    var rows = 0;

    var connection = new mssql.Connection(sqlConfig, function (err) {
        if (err) {
            console.log(err);
            return;
        }

        var request = connection.request();
        request.stream = true;

        request.query(candidateSourceSQL, function (err, recordSet) {
            if (err) {
                console.log(err);
                return;
            }

            console.log(recordSet);
        });

        request.on('row', function(row) {
            console.log(row);
            data_pump.from().writeAsync(row);
            rows++;
        });

        request.on('recordset', function(columns) {
            // Emitted once for each recordset in a query
            console.log(columns);

        });

        request.on('done', function (err, returnValue) {
            connection.close();
            console.log(rows);
            data_pump.from().seal();
        });

    });
    // Setup the data pump
    var data_pump = new datapumps.Pump().from(new datapumps.Buffer({size: 2000}));

    //Process the Post operation
    data_pump
        .mixin(datapumps.mixin.RestMixin)
        .process(function (data) {

            var record = '{ '+
                '"password": "some password", ' +
                '"is_internal": false, ' +
                '"is_active": false, ' +
                '"is_willing_to_relocate": true, ' +
                '"name": { ' +
                '"first": "' + data.FirstName + '" ' +
                (data.MiddleInitial ? ',"middle": "' + data.MiddleIntial + '" ' : '') +
                ',"last": "' + data.LastName + '" ' +
                    //(data)
                    //  ',"prefix": { ' +
                    //      "id": "d5b19770-00a8-43b8-a252-af24b416d21c"
                    //  }
                '}, '+
                '"contact_info": { ' +
                '"email": "' + data.Email + '", ' +
                '"phone": { ' +
                '"primary": "' + data.PrimaryPhone + '"' +
                (data.SecondaryPhone ? ',"secondary": "' + data.SecondaryPhone + '" ' : '') +

                '},' +
                '"address": { ' +
                '"line1": "' + data.Address1 + '", ' +
                (data.Address2 ? '"line2": "' + data.Address2 + '",' : '') +

                '"city": "' + data.City + '", '+
                '"state": { '+
                '"code": "' + data.State+ '" '+
                '}, ' +
                '"postal_code": "' + data.Zip+ '",' +
                '"country": { ' +
                '"code": "USA" ' +
                '}'+
                '}'+
                '}'+
                '}';

            var test_record_json = JSON.parse(record);

            return this.postJson(rec14APIUrlCandidates, test_record_json, {
                    headers: {
                        'Authorization': 'Bearer ' + rec14AuthToken,
                        'Accept': 'application/vnd.xxxx+json; version=2',
                        'Content-Type': 'application/json'
                    },
                    rejectUnauthorized: false,
                    followRedirects: true
            }).then(function(response) {
                    console.log(response.result);
                    console.log(response.statusCode);
                    
                    return this.copy(response);
                }.bind(this));

        }).logErrorsToConsole().on('end', function() {
        console.log('Pumped everything, and all my output buffers are empty. Bye.');
        }).start().whenFinished().then(function(){
            console.log('finished!!!!');
        });

});

**Comment by thxmike** [comment]
I have also noticed that when I remove the bind(this) on the data_pump.postJson promise, I am able to get to the whenfinished() promise and the on end event but there is an error "Error in pump (root): TypeError: undefined is not a function" It appears to be something with the bind

**Comment by novaki** [comment]
The problem was that you write into the output buffer of your last pump (.copy() method copies data to the output buffer). A pump finishes when its input and output buffers become empty. In the above example you did not read the output buffer of your last pump, so it never finishes.
