### ISSUE TITLE
Can't access failures log when is not a pump problem

### ISSUE THREAD

**Issue by ildella** [agmen-hu/node-datapumps#20]
Hi, I have this scenario in which I use RestMixin to POST some data to an API. 
From datapumps point of view, the POST is ok whatever the HTTP response status code is. I'd like to have the ability to intercept the response and log an error if something different than 200 or 201 happens. 

I cannot understand how to achieve this with datapumps, if it would be possible to update the README close to where is explained how to do this: 

  .logErrorsToConsole()
  .run()
    .then(function() {
      console.log("Done writing contacts to file");
  });

that is good but not enough for my purpose. Thanks.

**Comment by novaki** [comment]
Hi, the promise returned by `.run()` resolves when the whole pump finishes, so you should handle that kind of errors in `.process() instead`:
```coffee
pump
  .process (data) ->
    @post '...'
      .then (response) ->
        # here you have response.statusCode, and can handle it. The response is generated by the restler library
```

You can throw exception on error (it will be logged but the etl process will continue until your error buffer is full), or maybe retry the query.

I think the [RestMixin](http://agmen-hu.github.io/node-datapumps/docs/mixin/RestMixin.html) documentation needs update to be clear on this, I will not close this issue until I've updated it.

**Comment by ildella** [comment]
thanks, that will do the job.
