### ISSUE TITLE
ExcelWriterMixin - Streaming / memory handling for very large files 

### ISSUE THREAD

**Issue by CreativeTransmissions** [agmen-hu/node-datapumps#35]
Hi there,

Could you please advise whether exporting a very large number of rows (100,000 +) from MySQL will cause the ExcelWriterMixin to build the whole file in memory before creating the file, or if it will stream the output row by row, freeing memory as it goes?

Many thanks.

**Comment by novaki** [comment]
Hi,

Unfortunately, we could not find any streaming Excel lib when we developed the ExcelWriterMixin, so it buffers the whole the file in the memory at the moment. Feel free to upgrade or replace the mixin to be able to stream results.

**Comment by CreativeTransmissions** [comment]
No problem. Looks like a great project anyway. Thanks for letting me know!
